--2019.07.11

--GUESTBOOK DDL - 방명록 데이터 베이스

CREATE TABLE GUESTBOOK_MASSAGE (
    MESSAGE_ID NUMBER(6) CONSTRAINT GM_MID_PK PRIMARY KEY,
    GUEST_NAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(30) NOT NULL,
    MESSAGE BLOB NOT NULL
)

CREATE SEQUENCE GM_MID_SEQ;