--2019.07.11

--GUESTBOOK DDL - 방명록 데이터 베이스

CREATE TABLE GUESTBOOK_MESSAGE (
    MESSAGE_ID NUMBER(6) CONSTRAINT GM_MID_PK PRIMARY KEY,
    GUEST_NAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(30) NOT NULL,
    MESSAGE long NOT NULL
);

drop table GUESTBOOK_MESSAGE;

desc GUESTBOOK_MESSAGE;

select * from GUESTBOOK_MESSAGE order by message_id;

CREATE SEQUENCE GM_MID_SEQ;
drop sequence gm_mid_seq;

INSERT INTO GUESTBOOK_MESSAGE (MESSAGE_ID, GUEST_NAME, PASSWORD, MESSAGE)
VALUES (GM_MID_SEQ.nextval, ?, ?, ?);
            
INSERT INTO GUESTBOOK_MESSAGE (MESSAGE_ID, GUEST_NAME, PASSWORD, MESSAGE)
VALUES (GM_MID_SEQ.nextval, Arin, 7934, 안녕반가워);

